### ISSUE TITLE
Remove obsolete branches

### ISSUE THREAD

**Issue by iulusoy** [han16nah/my-ssd-test-repo#23]
Looks good already! You have all the necessary files there and the repo is nice and clean. Looks like the module is also slowly taking shape. One thing I noticed is that you have lots of open branches, I recommend deleting the ones you don't use anymore. You can delete them on GitHub, but you also need to delete them on your local machine (remember, you have a complete copy of the repo locally). You can do so using `git fetch -p` (this will prune the branches), sometimes you may have to do `git branch -d mybranch` of even using a capital D, if there are changes you did not want to commit.
You can also delete them from VSCode on the git tab, clicking on the three dots in the top right of the git bar, and selecting "Branch", etc.

**Comment by han16nah** [comment]
Thanks @iulusoy for the reminder 🙂 

@vivienzahs @rdlaura I removed the branches on the remote.
I also deleted any obsolete branches for me locally. Once you have done the same, feel free to comment here or just close the issue.
